[package]
name = "rust_basic_matrix"
description = "A simple N*N Matrix data structure to help with constructing graphs"
license = "MIT"
version = "0.0.3"
authors = [ "Blake Loring <blake_l@parsed.uk>" ]
